.\" Manpage for mccbs.service.
.\" Contact michael.reed33+mccbs@gmail.com to correct errors or typos.
.TH mccbs.service 8 "2013-06-26" "1.0" "mccbs.service man page"
.SH NAME
mccbs.service \- Minecraft Craftbukkit Service
.SH SYNOPSIS
.SS systemd scripts:
Comming Soon
.SH DESCRIPTION
mccbs.service is a systemd service ported from an initd script for a minecraft craftbukkit server. 
.SH OPTIONS
Comming Soon
.SH EXIT STATUS
Comming Soon
.SH SEE ALSO
mccbs.conf(5)
.SH BUGS
No known bugs.
.SH EXAMPLE
Comming Soon
.SH AUTHOR
Michael J. Reed (michael.reed33+mccbs@gmail.com)
