.\" Manpage for mccbs.conf.
.\" Contact michael.reed33+mccbs@gmail.com to correct errors or typos.
.TH mccbs.conf 8 "2013-06-26" "1.0" "mccbs.conf man page"
.SH NAME
mccbs.conf \- Minecraft Craftbukkit Service
.SH SYNOPSIS
.SS systemd scripts:
Comming Soon
.SH DESCRIPTION
mccbs.conf contains configuration information for mccbs.service, a systemd service ported from an initd script for a minecraft craftbukkit server. 
.SH OPTIONS
Comming Soon
.SH EXIT STATUS
Comming Soon
.SH SEE ALSO
mccbs.service(8)
.SH BUGS
No known bugs.
.SH EXAMPLE
Comming Soon
.SH AUTHOR
Michael J. Reed (michael.reed33+mccbs@gmail.com)
